server:
  port: 8081

spring:
  application:
    name: consumer-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consumer-service
        instance-id: consumer-service-${spring.application.name}-${server.port}
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
  datasource:
    url: jdbc:postgresql://localhost:5432/consumerdb
    username: microservice
    password: microservice
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
