server:
  port: 8761

spring:
  application:
    name: discovery-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: discovery-service
        instance-id: discovery-service-instance-1
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info
