server:
  port: 8090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/${segment}

        - id: swagger-consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/consumer-service/swagger-ui.html
            - Path=/consumer-service/v3/api-docs/**
          filters:
            - RewritePath=/consumer-service/(?<segment>.*), /${segment}

  consul:
    host: localhost
    port: 8500
    discovery:
      enabled: true

springdoc:
  swagger-ui:
    urls:
      - name: consumer-service
        url: /consumer-service/v3/api-docs


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

