server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/api/consumers/**
          filters:
            - RewritePath=/api/consumers/(?<segment>.*), /$\{segment}

  application:
    name: gateway-service
  consul:
    host: localhost
    port: 8500
    discovery:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

