server:
  port: 8090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}

        - id: swagger-for-consumer
          uri: lb://consumer-service
          predicates:
            - Path=/consumer-service/swagger-ui.html
            - Path=/consumer-service/swagger-ui/**
            - Path=/consumer-service/v3/api-docs/**
          filters:
            - RewritePath=/consumer-service/(?<segment>.*), /${segment}

        - id: spring-security-service
          uri: lb://spring-security-service
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/users/${segment}

      default-filters:
        - TokenRelay=

    discovery:
      enabled: true
      locator:
        enabled: true
        lower-case-service-id: true

  consul:
    host: localhost
    port: 8500
    discovery:
      enabled: true
      register: true
      prefer-ip-address: true

springdoc:
  swagger-ui:
    urls:
      - name: consumer-service
        url: /consumer-service/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
