server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/api/consumer/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/microservice-realm
