spring:
  application:
    name: spring-security-service
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security
    username: microservice
    password: microservice
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 7071
